stages:
  - lint
  - name: test_roles
    if: type IN (push, cron)
  - name: test_docker
    if: type IN (push, cron)

language: python

sudo: required

services:
  - docker

addons:
  apt:
    update: true

before_install:
  - cp inventory.local inventory
  - cp extra_vars.yml.ci extra_vars.yml
  - sed -ri "s:AWS_ACCESS_KEY:$AWS_ACCESS_KEY:" extra_vars.yml
  - sed -ri "s:AWS_SECRET_KEY:$AWS_SECRET_KEY:" extra_vars.yml
jobs:
  include:
    - stage: lint
      script: >
        ansible-playbook site.yml -i inventory --extra-vars "@extra_vars.yml"
        --check --skip-tag greengrass-core
    - stage: test_roles
      env:
        - AWS_ARGS=--no-verify-ssl
      script:
        - ansible-playbook dev.yml -i inventory --extra-vars "@extra_vars.yml"
        - cd roles/greengrass-init/tests
# skip: SSL error        - ansible-playbook test.yml -i inventory -vv
    - stage: test_docker
      script:
        - docker build -t vmware/ansible-aws-greengrass:test -f Dockerfile.testing .
        - >
          docker run -it --rm vmware/ansible-aws-greengrass:test site.yml
          -i inventory -v --extra-vars "@extra_vars.yml"
