stages:
  - lint
  - name: test_roles
    if: type IN (push, cron)
  - name: test_docker
    if: type IN (push, cron)

language: python

sudo: required

services:
  - docker

addons:
  apt:
    update: true

before_install:
  - cp inventory.local inventory
  - mkdir -p group_vars/all
  - cp extra_vars.yml.ci vars.yml
  - sed -ri "s:AWS_ACCESS_KEY:$AWS_ACCESS_KEY:" vars.yml
  - sed -ri "s:AWS_SECRET_KEY:$AWS_SECRET_KEY:" vars.yml
  - mv vars.yml group_vars/all
jobs:
  include:
    - stage: lint
      script:
        - ansible-galaxy install -r requirements.yml -p roles
        - >
          ansible-playbook site.yml -i inventory
          --check --skip-tag greengrass-core
    - stage: test_roles
      env:
        - AWS_ARGS=--no-verify-ssl
      script:
        - ansible-galaxy install -r requirements.yml -p roles
        - >
          ansible-playbook roles/greengrass-init/tests/test.yml
          -i roles/greengrass-init/tests/inventory -vv || echo 'Not OK!'
    - stage: test_docker
      script:
        - >
          docker build -t vmware/ansible-aws-greengrass:test
          -f Dockerfile.testing .
        - >
          docker run -it --rm vmware/ansible-aws-greengrass:test site.yml
          -i inventory -v
