# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 or GPL-3.0-only
---
- src: vmware.ansible_role_greengrass_awscli
  name: vmware.awscli
- src: vmware.greengrass_init
  name: greengrass-init
