# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 or GPL-3.0-only
---
# Variables for customizing the deploy of lambda functions

# This is the name for the role that allows lambda execution from greengrass.
# You may wish to customize with more permissions and a different name.
#lambda_role_name: "Lambda-Greengrass-S3"

# Preferred region.
#aws_region: us-east-1

# An S3 bucket is required; uploading a zip directly is too slow and exceeds
# the signature threshold using the CLI.
#staging_s3_bucket: greengrass-lambdas

# Set to true to bypass upload, if source is already on S3
#skip_s3_uploads: false

#lambdas: []

# Sample lambda setting
# lambdas:
#   - name: some_function_name
#     description: Describe the function
#     zip: /path/to/source/of/function.zip
#     handler: module.function_handler
#     runtime: python2.7
#     version: 1
#     id: function_id1

# Set this if desired, otherwise will be generated
# function_definition_name:
